name: 'pdflatex'

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: pdflatex
        uses: xu-cheng/latex-action@latest
        with:
          root_file: src/main.tex
          compiler: pdflatex
          args: -output-dir=out/ -no-shell-escape
    
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: main.pdf
          path: out/main.pdf
