name: 'pdflatex'

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: src/main.tex
          compiler: pdflatex
          args: -output-dir=out/