name: 'pdflatex'

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: pdflatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/main.tex
          args: -pdf -outdir=out/
    
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: main.pdf
          path: out/main.pdf

      - name: generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::LaTeXBuild-$(date +"%Y.%m.%d_%H-%M")"
      
      - name: release pdf
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: out/main.pdf
