name: 'pdflatex'

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: generate output
        run: pdflatex --output-dir out/ src/main.tex